### ISSUE TITLE
2017 image links

### ISSUE THREAD

**Issue by erex** [distanceworkshops/stand-intermed-2017#1]
Laura received this query this morning:

> I’ve been using your Intermediate Distance Sampling course online: http://workshops.distancesampling.org/stand-intermed-2017/practicals/bookdown/index.html. It’s been a massive massive help – thanks so much for making all this helpful advice and easy-to-follow steps available. One question I have about it, the images embedded on many pages aren’t displaying. I’ve tried to open them in separate tabs and it links to a github page that can no longer be found. Is there any way of accessing the whole lot as a pdf, or redirecting me to the github page or something? The instructions and code are great, but where it’s data specific being able to see the example outputs so I know what I’m aiming for would be hugely helpful.

Poking about, the html was created with Bookdown.  There are three subdirectories containing figures for various portions of the workshop.  Links to images in two of the directories work fine, but links to the directory:

```
https://workshops.distancesampling.org/stand-intermed-2017/practicals/bookdown/_main_files/figure-html
```
are broken, even though proper image files appear within that directory.

I'm afraid I don't know the solution; all appears to be in order.  The one oddity is this appearance of the directory structure:
![image](https://user-images.githubusercontent.com/330744/63223777-8cad0700-c1b2-11e9-8912-25b60ef14d2c.png)
Note the `_main_files` appears in grey??

**Comment by dill** [comment]
This appears to be fixed now, though don't understand why it was broken.

**Comment by erex** [comment]
thx Dave, couldn't understand the problem myself, that's why I decided not to muck around and make matters worse
